### ISSUE TITLE
Authentication fails with colon in password

### ISSUE THREAD

**Issue by Sakorah** [0xHiteshPatel/f5-postman-workflows#10]
Hi,

the authentication fails if the password contains a colon, as the variables are not enclosed within quotes. 

So this fails:
```
{
  "username": {{bigip_username}},
  "password": {{bigip_password}},
  "loginProvidername":"tmos"
}
```

while as this works:
```
{
  "username": "{{bigip_username}}",
  "password": "{{bigip_password}}",
  "loginProvidername":"tmos"
}
```

This is within 1_Authenticate and "Authenticate and Obtain Token"

Greetings,
Eric

**Comment by 0xHiteshPatel** [comment]
Doh!  Will get that fixed.  Thanks for reporting it.
