### ISSUE TITLE
f5-postman-workflows install fails

### ISSUE THREAD

**Issue by tkam8** [0xHiteshPatel/f5-postman-workflows#11]
##### Issue
(udf2)
When trying to install the f5-postman-workflows into Postman Client for the first time, there is an error and leads to failed installation, and global variables not populated

http://f5-automation-labs.readthedocs.io/en/v2.0/class1/module4/lab1.html 

##### POST
```
http://closure-compiler.appspot.com/compile?code_url=https://raw.githubusercontent.com/0xHiteshPatel/f5-postman-workflows/{{_f5_framework_branch}}/framework/src/f5-postman-workflows.js&compilation_level=SIMPLE_OPTIMIZATIONS&output_format=json&output_info=warnings&output_info=errors&output_info=compiled_code

```
##### Body
```
{"compiledCode":"","errors":[{"type":"JSC_ARGUMENTS_CALLEE_FORBIDDEN","file":"https://raw.githubusercontent.com/0xHiteshPatel/f5-postman-workflows/master/framework/src/f5-postman-workflows.js","lineno":508,"charno":26,"error":"\"arguments.callee\" cannot be used in strict mode","line":"        console.log('[' + arguments.callee.caller.name + '] ' + msg);"}]}

```

![image](https://cloud.githubusercontent.com/assets/19481266/26390714/ba83a2f6-409a-11e7-8306-43e293f2da9f.png)

##### f5-postman-workflows.js  lines 506-511
```javascript
function f5_debug(msg) {
    if(postman.getGlobalVariable("_f5_debug") == "1") {
        console.log('[' + arguments.callee.caller.name + '] ' + msg);
    }
    return;
}
```

Check f5-postman-workflows Version completes as expected:

![image](https://cloud.githubusercontent.com/assets/19481266/26390740/ce3e683a-409a-11e7-93e7-5710c2a83db6.png)

Global vars:
![image](https://cloud.githubusercontent.com/assets/19481266/26391005/e6756268-409b-11e7-9a02-68845c316520.png)

**Comment by jmcalalang** [comment]
Same error on non-UDF Postman Version 4.10.7 (4.10.7), ill test more later today

**Comment by tkam8** [comment]
Here is the version info:

Postman for Windows
Version 4.10.7
win32 10.0.14393 / x64
-----
I also downgraded to below version but still same 

Postman for Windows
Version 4.10.3  <---3/2/2017 release used to building the UDF lab
win32 10.0.14393 / x64
